"""
Decision Support System UI Module for AgriSense.
Integrates multi-model inference across WEKA J48, Naive Bayes, Apriori Rules,
K-Means Clustering, Yield Regression, and Data-Driven Fertilizer Recommendation.
"""

import streamlit as st
import pandas as pd
from utils.helpers import render_header, render_metric_card
from decision_support.engine import AgriculturalDecisionSupportEngine

def render_decision_intelligence_page(df_raw: pd.DataFrame):
    """Render Agronomic Decision Intelligence Advisory dashboard with Fertilizer Recommendations."""
    render_header(
        "Decision Intelligence Workspace",
        "Analyze agricultural conditions and combine available model and historical-data insights."
    )

    # Disclaimer Box
    st.info("""
    **AGRONOMIC DECISION SUPPORT DISCLAIMER**:
    The recommendations and estimations generated by AgriSense are data-driven predictions computed from historical training datasets using machine learning algorithms. 
    They are intended solely for **decision-support guidance** and should be validated against local soil testing reports and professional agricultural extension advice.
    """)

    st.markdown("### Agricultural Land & Microclimate Conditions Input")

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        in_n = st.number_input("Nitrogen (N kg/ha)", min_value=0.0, max_value=250.0, value=90.0, step=5.0)
        in_p = st.number_input("Phosphorus (P kg/ha)", min_value=0.0, max_value=250.0, value=42.0, step=5.0)
    with c2:
        in_k = st.number_input("Potassium (K kg/ha)", min_value=0.0, max_value=350.0, value=43.0, step=5.0)
        in_temp = st.number_input("Average Temperature (°C)", min_value=0.0, max_value=50.0, value=23.5, step=0.5)
    with c3:
        in_hum = st.number_input("Relative Humidity (%)", min_value=0.0, max_value=100.0, value=82.0, step=1.0)
        in_ph = st.number_input("Soil pH Level", min_value=0.0, max_value=14.0, value=6.5, step=0.1)
    with c4:
        in_rain = st.number_input("Annual Rainfall (mm)", min_value=0.0, max_value=600.0, value=202.0, step=5.0)
        run_dss_btn = st.button("Generate Decision Advisory")

    inputs_dict = {
        "N": in_n, "P": in_p, "K": in_k,
        "temperature": in_temp, "humidity": in_hum,
        "ph": in_ph, "rainfall": in_rain
    }

    # Execute Multi-Model Inference
    advisory = AgriculturalDecisionSupportEngine.generate_advisory(df_raw, inputs_dict)
    fert_rec = advisory.get("fertilizer_recommendation", {})

    st.markdown("---")

    # Multi-Model Recommendation Cards
    m1, m2, m3, m4 = st.columns(4)
    with m1:
        render_metric_card("Target Crop (NB)", f"{advisory['nb_predicted_crop'].upper()}", f"Confidence: {advisory['nb_confidence_pct']}%")
    with m2:
        fert_title = fert_rec.get("recommended_fertilizer", "N/A") if fert_rec.get("status") == "SUCCESS" else "Insufficient Data"
        render_metric_card("Recommended Fertilizer", fert_title, f"Primary Deficit: {fert_rec.get('primary_deficiency', 'N/A')}")
    with m3:
        render_metric_card("Assigned Land Cluster", f"{advisory['assigned_cluster']}", "K-Means segmentation")
    with m4:
        render_metric_card("Estimated Crop Yield", f"{advisory['estimated_yield']} Tons / Ha", "Random Forest Regressor")

    st.markdown("---")

    # Tabs Layout
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "Agricultural Analysis & Domain Synthesis",
        "Data-Driven Fertilizer Recommendation",
        "Matched Association Rules",
        "Cluster Profile & Land Segment",
        "Historical Dataset Comparison"
    ])

    with tab1:
        st.subheader("Data-Driven Agronomic Analysis")
        st.markdown(advisory["domain_synthesis"])

        st.markdown("### Model Consensus & Confidence Summary")
        consensus_str = "High Consensus" if advisory["j48_predicted_crop"].lower() == advisory["nb_predicted_crop"].lower() else "Divergent Predictions"
        st.write(f"- **Model Consensus Status**: **{consensus_str}**")
        st.write(f"- **WEKA J48 Recommendation**: **{advisory['j48_predicted_crop'].title()}**")
        st.write(f"- **Gaussian Naive Bayes Recommendation**: **{advisory['nb_predicted_crop'].title()}** ({advisory['nb_confidence_pct']}% confidence)")
        st.write(f"- **Predicted Yield Potential**: **{advisory['estimated_yield']} Tons / Hectare**")

        st.markdown("### Indian Mandi Market Intelligence Lookup (Agmarknet)")
        from data.india.provider import IndianAgriculturalDataProvider
        mkt_info = IndianAgriculturalDataProvider.get_crop_mandi_info(advisory["nb_predicted_crop"])
        if mkt_info.get("status") == "SUCCESS":
            st.write(f"- **Benchmark APMC Mandi Modal Price**: **₹ {mkt_info['latest_price']:,.2f} / Quintal** ({mkt_info['market_apmc']}, {mkt_info['district']}, {mkt_info['state']})")
            st.write(f"- **Mandi Price Trend**: **{mkt_info['price_trend']}** | **Arrival Date**: **{mkt_info['arrival_date']}**")
            st.caption(f"Provenance: {mkt_info['provenance']}")
        else:
            st.write("- **APMC Mandi Price**: Indian market registry lookup available in Market Intelligence tab.")


    with tab2:
        st.subheader("Data-Driven Fertilizer Recommendation Engine")
        st.caption("Fertilizer recommendations derived from historical fertilizer telemetry dataset patterns and nutrient deficit matching:")

        if fert_rec.get("status") == "SUCCESS":
            f_col1, f_col2, f_col3, f_col4 = st.columns(4)
            with f_col1:
                render_metric_card("Selected Crop", f"{fert_rec['crop']}", "Target crop variety")
            with f_col2:
                render_metric_card("Fertilizer Product", f"{fert_rec['recommended_fertilizer']}", "Optimal formulation")
            with f_col3:
                render_metric_card("Application Rate", f"{fert_rec['recommended_dose_kg_ha']} kg/ha", "Recommended dosage")
            with f_col4:
                render_metric_card("Pattern Match Confidence", f"{fert_rec['confidence_score_pct']}%", f"Sample Support: {fert_rec['sample_support_count']} records")

            st.markdown("### Supporting Data & Mined Pattern")
            st.code(fert_rec["supporting_pattern"], language="text")

            st.markdown("### Agronomic Rationale & Explanation")
            st.markdown(fert_rec["explanation"])
        else:
            st.warning(fert_rec.get("message", "Insufficient historical data for a reliable recommendation."))

    with tab3:
        st.subheader("Matched Association Rules from Dataset")
        st.caption("Co-occurrence patterns mined via Apriori matching your input nutrient and environmental parameters:")
        matched = advisory["matched_rules"]
        if matched:
            rules_df = pd.DataFrame(matched)
            rules_df.columns = ["Antecedents (IF)", "Consequents (THEN)", "Confidence", "Lift"]
            st.dataframe(rules_df, use_container_width=True)
        else:
            st.info("No matching high-lift association rules found for the specified input combination.")

    with tab4:
        st.subheader("Assigned Cluster Profile & Mean Characteristics")
        st.caption(f"Un-scaled mean attribute values for assigned **{advisory['assigned_cluster']}**:")
        prof = advisory["cluster_profile"]
        prof_df = pd.DataFrame([prof])
        st.dataframe(prof_df, use_container_width=True)

    with tab5:
        st.subheader("Historical Telemetry Comparison")
        st.caption(f"Comparison of your input values against historical records for **{advisory['nb_predicted_crop'].title()}** in dataset:")

        hist = advisory["historical_stats"]
        comp_df = pd.DataFrame([
            {"Parameter": "Nitrogen (N kg/ha)", "Entered Input": in_n, "Historical Dataset Mean": hist["avg_nitrogen"], "Variance": round(in_n - hist["avg_nitrogen"], 2)},
            {"Parameter": "Annual Rainfall (mm)", "Entered Input": in_rain, "Historical Dataset Mean": hist["avg_rainfall"], "Variance": round(in_rain - hist["avg_rainfall"], 2)},
            {"Parameter": "Soil pH", "Entered Input": in_ph, "Historical Dataset Mean": hist["avg_ph"], "Variance": round(in_ph - hist["avg_ph"], 2)}
        ])
        st.dataframe(comp_df, use_container_width=True)
        st.caption(f"Based on {hist['crop_sample_count']} historical dataset records for {advisory['nb_predicted_crop']}.")

render_decision_support_page = render_decision_intelligence_page

